---
- name: Install and configure Apache on web servers
  hosts: web
  become: true
  vars:
    apache_service: httpd
    web_root: /var/www/html

  tasks:
    - name: Update system packages
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: yes
      tags:
        - update

    - name: Install Apache web server
      ansible.builtin.yum:
        name: "{{ apache_service }}"
        state: present
      tags:
        - install

    - name: Ensure web root directory exists
      ansible.builtin.file:
        path: "{{ web_root }}"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'
      tags:
        - setup

    - name: Start and enable Apache service
      ansible.builtin.service:
        name: "{{ apache_service }}"
        state: started
        enabled: yes
      tags:
        - service

    - name: Configure firewall for HTTP (if firewalld is running)
      ansible.builtin.firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
      ignore_errors: yes
      tags:
        - firewall

    - name: Verify Apache is listening on port 80
      ansible.builtin.wait_for:
        port: 80
        timeout: 10
      tags:
        - verify

    - name: Display Apache status
      ansible.builtin.debug:
        msg: "✅ Apache installed and running successfully"
